export const opportunityStatusLabels = {
  watching: 'Watching',
  expectedSoon: 'Expected soon',
  open: 'Open / active',
  verifyManually: 'Verify manually',
};

export const confidenceLabels = {
  high: 'High',
  medium: 'Medium',
  needsReview: 'Needs review',
};

export const opportunityFilters = {
  categories: [
    'Internship',
    'Externship / insight series',
    'Winternship',
    'Conference funding',
    'Fellowship',
    'Internship-matching fellowship',
    'Scholarship',
    'Special program / resource',
    'Technical community',
    'Training program',
  ],
  audiences: [
    'College students',
    'Early-career engineers',
    'Graduate students',
    'Undergraduate students',
    'Women in tech',
    'Underrepresented students',
  ],
  classYears: ['Freshman', 'Sophomore', 'All class years'],
  seasons: ['Winter', 'Spring', 'Summer', 'Fall', 'Rolling'],
  funding: ['Funded', 'Free', 'Financial assistance', 'Paid stipend', 'Scholarship available', 'Travel support', 'Varies'],
  statuses: Object.keys(opportunityStatusLabels),
};

export const opportunities = [
  {
    id: 'microsoft-explore-watch',
    name: 'Microsoft Explore',
    organization: 'Microsoft',
    category: 'Internship',
    audience: ['Freshman', 'Undergraduate students'],
    classYears: ['Freshman'],
    tags: ['Software engineering', 'Underclassmen', 'Big tech', 'Summer internship'],
    eligibility:
      'First-year undergraduate students interested in software engineering. Confirm exact eligibility on the current Microsoft careers posting.',
    applicationUrl: 'https://careers.microsoft.com/',
    previousUrl: '',
    expectedOpeningMonth: 'Summer',
    openDate: 'Watch summer and early fall postings',
    season: 'Summer',
    deadline: 'Verify current posting',
    status: 'verifyManually',
    fundingAvailable: 'Paid stipend',
    locationType: 'Internship location varies',
    whyItMatters:
      'A classic freshman-targeted software engineering internship signal that helps underclassmen get industry experience before traditional junior-year recruiting.',
    prepNotes:
      'Track Microsoft careers, prepare a freshman-friendly project story, and watch for Explore-specific role titles rather than only generic SWE intern postings.',
    sourceNote:
      'Inspired by the underclassmen-internships repo taxonomy; official posting must be verified before sharing.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'needsReview',
  },
  {
    id: 'palantir-path-watch',
    name: 'Palantir Path',
    organization: 'Palantir',
    category: 'Internship',
    audience: ['Sophomore', 'Undergraduate students'],
    classYears: ['Sophomore'],
    tags: ['Software engineering', 'Underclassmen', 'Product engineering', 'Summer internship'],
    eligibility:
      'Typically positioned for sophomore students; confirm current eligibility and role availability on Palantir careers.',
    applicationUrl: 'https://www.palantir.com/careers/',
    previousUrl: '',
    expectedOpeningMonth: 'Summer',
    openDate: 'Watch summer and early fall postings',
    season: 'Summer',
    deadline: 'Verify current posting',
    status: 'verifyManually',
    fundingAvailable: 'Paid stipend',
    locationType: 'Internship location varies',
    whyItMatters:
      'A focused underclassmen internship path for students interested in product-heavy software engineering and complex customer-facing systems.',
    prepNotes:
      'Prepare systems/project examples and check whether the current cycle lists Path separately from standard internship roles.',
    sourceNote:
      'Inspired by the underclassmen-internships repo taxonomy; official posting must be verified before sharing.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'needsReview',
  },
  {
    id: 'nasa-internships-watch',
    name: 'NASA Internships',
    organization: 'NASA',
    category: 'Internship',
    audience: ['All class years', 'Undergraduate students', 'Graduate students'],
    classYears: ['All class years'],
    tags: ['Government', 'Research', 'Engineering', 'Many postings'],
    eligibility:
      'NASA internships include many postings with different class-year, citizenship, major, and location requirements.',
    applicationUrl: 'https://intern.nasa.gov/',
    previousUrl: '',
    expectedOpeningMonth: 'Rolling',
    openDate: 'Open year-round across postings',
    season: 'Rolling',
    deadline: 'Posting-specific',
    status: 'watching',
    fundingAvailable: 'Paid stipend',
    locationType: 'In-person, hybrid, or remote depending on posting',
    whyItMatters:
      'A broad underclassmen-friendly source because eligibility is posting-specific and some roles can fit students earlier than standard industry internships.',
    prepNotes:
      'Search by major, location, and class year. Save postings that explicitly include freshman or sophomore eligibility instead of assuming all NASA roles do.',
    sourceNote:
      'Included because the repo highlights NASA as a year-round source with many posting-specific requirements.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'medium',
  },
  {
    id: 'jane-street-fttp-watch',
    name: 'Focus on Trading and Technology Program',
    organization: 'Jane Street',
    category: 'Externship / insight series',
    audience: ['Freshman', 'Undergraduate students'],
    classYears: ['Freshman'],
    tags: ['Trading', 'Finance', 'Insight program', 'Quant'],
    eligibility:
      'Usually aimed at first-year students interested in trading and technology; confirm current cycle requirements on Jane Street careers.',
    applicationUrl: 'https://www.janestreet.com/join-jane-street/',
    previousUrl: '',
    expectedOpeningMonth: 'Fall',
    openDate: 'Watch fall and winter',
    season: 'Spring',
    deadline: 'Verify current program cycle',
    status: 'verifyManually',
    fundingAvailable: 'Varies',
    locationType: 'Insight program',
    whyItMatters:
      'A short early-exposure program that helps freshmen learn whether trading, math, finance, and technology environments are worth pursuing further.',
    prepNotes:
      'Prepare a concise explanation of interest in trading/technology and track separate insight-program pages, not only internship pages.',
    sourceNote:
      'Inspired by the repo section for externships and insight series.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'needsReview',
  },
  {
    id: 'google-summer-of-code',
    name: 'Google Summer of Code',
    organization: 'Google',
    category: 'Fellowship',
    audience: ['All class years', 'College students', 'Early-career engineers'],
    classYears: ['All class years'],
    tags: ['Open source', 'Mentorship', 'Summer', 'Stipend'],
    eligibility:
      'Open-source contribution program for new and beginner contributors, with eligibility determined by the current program rules.',
    applicationUrl: 'https://summerofcode.withgoogle.com/',
    previousUrl: '',
    expectedOpeningMonth: 'Spring',
    openDate: 'Typically spring application cycle',
    season: 'Summer',
    deadline: 'Verify current annual timeline',
    status: 'watching',
    fundingAvailable: 'Paid stipend',
    locationType: 'Remote',
    whyItMatters:
      'A strong nontraditional path for underclassmen who need credible technical experience without waiting for a company internship.',
    prepNotes:
      'Review past organizations early, make small open-source contributions before applying, and choose projects where your current skills can compound.',
    sourceNote:
      'Inspired by the repo fellowship section and kept because it supports an underclassmen-friendly experience path.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'medium',
  },
  {
    id: 'outreachy',
    name: 'Outreachy',
    organization: 'Outreachy',
    category: 'Fellowship',
    audience: ['All class years', 'Underrepresented students', 'Early-career engineers'],
    classYears: ['All class years'],
    tags: ['Open source', 'Remote', 'Diversity in tech', 'Stipend'],
    eligibility:
      'Open-source internship program for people subject to systemic bias and underrepresentation in technology; confirm current eligibility rules before applying.',
    applicationUrl: 'https://www.outreachy.org/',
    previousUrl: '',
    expectedOpeningMonth: 'Winter',
    openDate: 'Watch winter and late summer cycles',
    season: 'Rolling',
    deadline: 'Cycle-specific',
    status: 'watching',
    fundingAvailable: 'Paid stipend',
    locationType: 'Remote',
    whyItMatters:
      'A practical route into open-source contribution, mentorship, and paid technical experience for students who may not yet have internship access.',
    prepNotes:
      'Read eligibility carefully, complete initial applications early, and budget time for contribution periods before final project selection.',
    sourceNote:
      'Inspired by the repo fellowship section and kept as a high-signal open-source pathway.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'medium',
  },
  {
    id: 'virtu-womens-winternship-watch',
    name: "Women's Winternship",
    organization: 'Virtu Financial',
    category: 'Winternship',
    audience: ['Sophomore', 'Women in tech', 'Undergraduate students'],
    classYears: ['Sophomore'],
    tags: ['Winter break', 'Trading', 'Finance', 'Women in tech'],
    eligibility:
      'Short winter educational program historically aimed at sophomore women; verify current posting and requirements.',
    applicationUrl: 'https://www.virtu.com/careers/',
    previousUrl: '',
    expectedOpeningMonth: 'Fall',
    openDate: 'Watch fall postings',
    season: 'Winter',
    deadline: 'Verify current posting',
    status: 'verifyManually',
    fundingAvailable: 'Varies',
    locationType: 'Winter program',
    whyItMatters:
      'Winternships are useful underclassmen leverage because they create a real signal during a school break without requiring a full summer internship.',
    prepNotes:
      'Search company careers for winternship language and prepare finance-plus-technology interest notes before fall deadlines.',
    sourceNote:
      'Inspired by the repo winternship section.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'needsReview',
  },
  {
    id: 'forage-virtual-experience',
    name: 'Virtual Work Experience Programs',
    organization: 'Forage',
    category: 'Special program / resource',
    audience: ['All class years', 'College students', 'Undergraduate students'],
    classYears: ['All class years'],
    tags: ['Virtual experience', 'Career exploration', 'Company simulations', 'Beginner-friendly'],
    eligibility:
      'Students can explore company-backed virtual experience programs; exact format and requirements vary by program.',
    applicationUrl: 'https://www.theforage.com/',
    previousUrl: '',
    expectedOpeningMonth: 'Rolling',
    openDate: 'Open year-round',
    season: 'Rolling',
    deadline: 'Program-specific',
    status: 'open',
    fundingAvailable: 'Free',
    locationType: 'Virtual',
    whyItMatters:
      'Helpful for freshmen and sophomores who need low-friction exposure to industry workflows before applying to selective internships.',
    prepNotes:
      'Use this as exploration and language-building, then convert completed programs into stronger project and interview stories.',
    sourceNote:
      'Inspired by the repo special programs and resources section.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'medium',
  },
  {
    id: 'acm-w-research-conference-scholarships',
    name: 'ACM-W Research Conference Scholarships',
    organization: 'ACM-W',
    category: 'Conference funding',
    audience: ['Women in tech', 'Undergraduate students', 'Graduate students'],
    classYears: ['All class years'],
    tags: ['Research conference', 'Travel support', 'CS research', 'Women in computing'],
    eligibility:
      'Undergraduate and graduate students in computer science or related computing programs, including students working on CS-related projects outside traditional CS departments.',
    applicationUrl: 'https://women.acm.org/scholarships/',
    previousUrl: '',
    expectedOpeningMonth: 'Rolling deadline groups',
    openDate: 'Rolling deadline groups',
    season: 'Rolling',
    deadline: 'Deadline groups vary by conference date',
    status: 'open',
    fundingAvailable: 'Travel support',
    locationType: 'Conference travel',
    whyItMatters:
      'Useful for students who want to attend research conferences before they have a large travel budget or a strong academic network.',
    prepNotes:
      'Pick the conference first, then prepare a clear statement of why attendance supports your academic or industry path. Ask an advisor early for the support letter.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'high',
  },
  {
    id: 'codepath-career-ready-courses',
    name: 'Career-Ready Courses',
    organization: 'CodePath',
    category: 'Training program',
    audience: ['College students', 'Undergraduate students', 'Underrepresented students'],
    classYears: ['All class years'],
    tags: ['Technical interview prep', 'Applied AI', 'Cybersecurity', 'Web development'],
    eligibility:
      'Students seeking no-cost technical courses and career preparation, with pathways varying by course and application cycle.',
    applicationUrl: 'https://www.codepath.org/courses',
    previousUrl: '',
    expectedOpeningMonth: 'Varies by term',
    openDate: 'Varies by term',
    season: 'Fall',
    deadline: 'Varies by course cycle',
    status: 'open',
    fundingAvailable: 'Free',
    locationType: 'Virtual',
    whyItMatters:
      'Strong practical option for students who need structured technical practice, portfolio projects, and recruiting preparation outside standard coursework.',
    prepNotes:
      'Match the pathway to the next bottleneck: interview prep, AI projects, cybersecurity, or web development. Save the application portal and term deadline.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'high',
  },
  {
    id: 'mlh-fellowship',
    name: 'MLH Fellowship',
    organization: 'Major League Hacking',
    category: 'Fellowship',
    audience: ['College students', 'Early-career engineers', 'Undergraduate students'],
    classYears: ['All class years'],
    tags: ['Open source', 'Remote', 'Software engineering', 'Production engineering'],
    eligibility:
      'Aspiring software engineers choosing from fellowship tracks such as software engineering, production engineering, and Web3 engineering.',
    applicationUrl: 'https://fellowship.mlh.com/',
    previousUrl: 'https://fellowship.mlh.io/',
    expectedOpeningMonth: 'Varies by cohort',
    openDate: 'Varies by cohort',
    season: 'Rolling',
    deadline: 'Varies by start date',
    status: 'watching',
    fundingAvailable: 'Paid stipend',
    locationType: 'Remote',
    whyItMatters:
      'Internship-alternative experience with real open-source or partner-backed projects, mentors, peers, and a concrete portfolio signal.',
    prepNotes:
      'Prepare a technical project story, GitHub links, and examples of collaboration. Track cohort start dates because timing changes by program track.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'high',
  },
  {
    id: 'coding-it-forward-fellowship',
    name: 'Coding it Forward Fellowship',
    organization: 'Coding it Forward',
    category: 'Internship-matching fellowship',
    audience: ['College students', 'Graduate students', 'Early-career engineers'],
    classYears: ['All class years'],
    tags: ['Civic tech', 'Public interest tech', 'Software engineering', 'Product', 'Data'],
    eligibility:
      'Early-career technologists interested in cybersecurity, data, design, product management, or software engineering in government offices.',
    applicationUrl: 'https://codingitforward.com/fellowship',
    previousUrl: '',
    expectedOpeningMonth: 'Winter',
    openDate: 'Watch October through winter',
    season: 'Winter',
    deadline: 'Usually seasonal; verify current cycle',
    status: 'watching',
    fundingAvailable: 'Paid stipend',
    locationType: 'United States',
    whyItMatters:
      'Distinctive path for students who want mission-driven technical work, government context, and projects with public-service impact.',
    prepNotes:
      'Prepare examples of technical ownership, communication with non-technical stakeholders, and interest in public interest technology.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'medium',
  },
  {
    id: 'rewriting-the-code-community',
    name: 'Student Community',
    organization: 'Rewriting the Code',
    category: 'Technical community',
    audience: ['Women in tech', 'College students', 'Early-career engineers'],
    classYears: ['All class years'],
    tags: ['Women in tech', 'Mentorship', 'Career events', 'Community'],
    eligibility:
      'University students and early-career women in tech, with community tracks for students and early-career professionals.',
    applicationUrl: 'https://rewritingthecode.org/',
    previousUrl: '',
    expectedOpeningMonth: 'Rolling',
    openDate: 'Rolling',
    season: 'Rolling',
    deadline: 'Membership is generally rolling; verify program-specific events',
    status: 'open',
    fundingAvailable: 'Free',
    locationType: 'Virtual and in-person events',
    whyItMatters:
      'High-signal community layer for women in tech that combines peer support, career programming, company access, and practical resources.',
    prepNotes:
      'Join the community first, then watch the member portal, events calendar, and company programs for higher-leverage opportunities.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'high',
  },
  {
    id: 'colorstack-membership',
    name: 'ColorStack Membership',
    organization: 'ColorStack',
    category: 'Technical community',
    audience: ['Underrepresented students', 'College students', 'Undergraduate students'],
    classYears: ['All class years'],
    tags: ['Black CS students', 'Latinx CS students', 'Community', 'Career fairs'],
    eligibility:
      'Black and Latinx computer science students looking for community, events, partner opportunities, and career support.',
    applicationUrl: 'https://www.colorstack.org/',
    previousUrl: '',
    expectedOpeningMonth: 'Rolling',
    openDate: 'Rolling',
    season: 'Rolling',
    deadline: 'Membership and events vary',
    status: 'open',
    fundingAvailable: 'Free',
    locationType: 'Virtual community and events',
    whyItMatters:
      'A strong example of community as opportunity infrastructure: Slack support, monthly workshops, resume visibility, and partner events.',
    prepNotes:
      'Join early, keep resume materials updated, and watch monthly opportunities and career fair announcements.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'high',
  },
  {
    id: 'generation-google-scholarship',
    name: 'Generation Google Scholarship',
    organization: 'Google',
    category: 'Scholarship',
    audience: ['Undergraduate students', 'Graduate students', 'Underrepresented students'],
    classYears: ['All class years'],
    tags: ['Google', 'Scholarship', 'Computer science', 'Financial support'],
    eligibility:
      'Students pursuing computer science or a closely related technical field; exact eligibility varies by region and annual cycle.',
    applicationUrl: 'https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship',
    previousUrl: '',
    expectedOpeningMonth: 'Spring',
    openDate: 'Watch spring scholarship cycle',
    season: 'Spring',
    deadline: 'Verify current annual cycle',
    status: 'verifyManually',
    fundingAvailable: 'Funded',
    locationType: 'Regional scholarship',
    whyItMatters:
      'Recognizable scholarship signal for students building a technical profile and looking for financial support tied to CS education.',
    prepNotes:
      'Verify the region-specific page, prepare transcript and resume materials, and draft short essays before the application window opens.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'needsReview',
  },
  {
    id: 'swe-scholarships',
    name: 'SWE Scholarships',
    organization: 'Society of Women Engineers',
    category: 'Scholarship',
    audience: ['Women in tech', 'Undergraduate students', 'Graduate students'],
    classYears: ['All class years'],
    tags: ['Engineering', 'Women in STEM', 'Scholarship', 'Society membership'],
    eligibility:
      'Women pursuing engineering, engineering technology, or related fields, with award criteria varying by scholarship.',
    applicationUrl: 'https://swe.org/scholarships-overview/',
    previousUrl: 'https://swe.org/scholarships/',
    expectedOpeningMonth: 'Winter',
    openDate: 'Watch winter scholarship cycle',
    season: 'Winter',
    deadline: 'Annual cycle; verify current dates',
    status: 'watching',
    fundingAvailable: 'Funded',
    locationType: 'Scholarship',
    whyItMatters:
      'Broad scholarship pool for women in engineering and related technical disciplines, often worth watching early in the year.',
    prepNotes:
      'Check whether SWE membership is needed, gather academic details, and shortlist scholarships that match year, major, and identity criteria.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'medium',
  },
  {
    id: 'nsf-reu-computer-science',
    name: 'Research Experiences for Undergraduates',
    organization: 'U.S. National Science Foundation',
    category: 'Fellowship',
    audience: ['Undergraduate students', 'College students'],
    classYears: ['All class years'],
    tags: ['Research', 'Summer', 'NSF', 'Graduate school prep'],
    eligibility:
      'Undergraduate students applying to REU Sites across science and engineering fields; exact requirements vary by host site.',
    applicationUrl: 'https://www.nsf.gov/funding/initiatives/reu',
    previousUrl: '',
    expectedOpeningMonth: 'Winter',
    openDate: 'Watch winter site deadlines',
    season: 'Winter',
    deadline: 'Site-specific deadlines often cluster in winter',
    status: 'expectedSoon',
    fundingAvailable: 'Paid stipend',
    locationType: 'Host-site dependent',
    whyItMatters:
      'High-value research pathway for undergraduates considering graduate school, research careers, or deeper technical specialization.',
    prepNotes:
      'Search for CS-adjacent REU sites, request references early, and tailor statements to each lab or research theme.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'medium',
  },
  {
    id: 'ghc-scholarship-watch',
    name: 'Grace Hopper Celebration Scholarship Watch',
    organization: 'AnitaB.org',
    category: 'Conference funding',
    audience: ['Women in tech', 'College students', 'Graduate students'],
    classYears: ['All class years'],
    tags: ['GHC', 'Conference funding', 'Career fair', 'Women in computing'],
    eligibility:
      'Students and technologists interested in attending Grace Hopper Celebration; scholarship criteria can change by year.',
    applicationUrl: 'https://ghc.anitab.org/',
    previousUrl: '',
    expectedOpeningMonth: 'Spring',
    openDate: 'Watch spring conference cycle',
    season: 'Spring',
    deadline: 'Verify current GHC scholarship cycle',
    status: 'verifyManually',
    fundingAvailable: 'Travel support',
    locationType: 'Conference',
    whyItMatters:
      'Major women-in-computing conference pathway with recruiting, community, technical sessions, and visibility for students.',
    prepNotes:
      'Track the official GHC site, school sponsorship paths, employer sponsorships, and local women-in-tech group funding options.',
    lastVerifiedDate: '2026-07-10',
    confidenceLevel: 'needsReview',
  },
];

export const opportunityLibraryStats = [
  { label: 'Seed records', value: String(opportunities.length) },
  { label: 'Categories', value: String(opportunityFilters.categories.length) },
  { label: 'Manual checks', value: 'Required' },
];
